import { Router, useRouter } from "next/router";
import { server } from "../../../config";
import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic";
import leftArrowRed from "../../../images/leftArrowRed.png";
import Image from "next/image";

const EditArticle = dynamic(() => import("../../../components/edit"), {
  ssr: false,
});

const Edit = ({ article }) => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div className="w-full h-full pt-4">
            <Head>
                <title>MEA</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href="/admin">
                <div className="mx-auto border-2 rounded-full sm:w-14 sm:h-14 md:w-16 md:h-16  w-11/12 h-18  border-[#E5E7EB] items-center text-center flex justify-center hover:border-[#F05454] duration-150 p-2 sm:ml-10">
                    <Image
                      src={leftArrowRed}
                      alt="picture"
                    />
                    </div>
            </Link>
            <div className="mx-auto sm:w-9/12 w-11/12 py-10">
                <EditArticle id={id} header={article.header} content={article.content} pictureUrl={article.pictureurl} router={router} />
            </div>
        </div>
  );
};

export const getServerSideProps = async (context) => {
  const res = await fetch(`${server}/api/articles/${context.params.id}`, {
    method: "GET",
  });
  try {
    const article = await res.json();
    return {
      props: {
        article,
      },
    };
  } catch (err) {
    console.log("Error: ", err.message);
    return err.message;
  }
};

export default Edit;
