import Head from "next/head";
import { React } from "react";
import dynamic from "next/dynamic";
import ArticleList from "../components/articlelist";
import { server } from "../config";
import Link from "next/link";

const CKEditorApp = dynamic(() => import("../components/ckeditor"), {
  ssr: false,
});

export default function Admin({ data }) {
  return (
    <div className="w-full h-full pt-10">
      <Head>
        <title>MEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto">
        <table className="table-auto border-2 mx-auto ">
          <thead>
            <tr>
              <th className="border-2">Başlık</th>
              <th className="border-2">Yayın Tarihi</th>
              <th className="border-2" colSpan="2">İşlem</th>
            </tr>
          </thead>
          <tbody>
            <ArticleList data={data} />
            <tr>
              <td colSpan="4">
                <Link href="/submitnew">
                  <button className="font-semibold hover:text-white outline-none  focus:border-green-400 hover:bg-green-400 duration-300 w-full h-20">Yeni Ekle +</button>
                </Link>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`${server}/api/admin/article`, {
    method: "GET",
  });
  try {
    const data = await res.json();

    return {
      props: {
        data,
      },
    };
  } catch (err) {
    console.log("Error: ", err.message);
    return err.message;
  }
}
