import Head from "next/head";
import { React, useEffect, useState } from "react";
import ArticleList from "../components/articlelist";
import { server } from "../config";

export default function Admin({ dataX }) {

  const [dataY, setDataY] = useState("");

  useEffect( () => {
    setDataY(dataX);
  },[]);

  return (
    <div className="w-full h-full pt-10">
      <Head>
        <title>MEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto w-9/12">
        
            <ArticleList data={dataY} />

      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`${server}/api/admin/article`, {
    method: "GET",
  });
  try {
    const dataX = await res.json();
    return {
      props: {
        dataX,
      },
    };
  } catch (err) {
    console.log("Error: ", err.message);
    return err.message;
  }
}
