import Head from "next/head";

import { React, useRef} from "react";

import dynamic from 'next/dynamic'

const CKEditorApp = dynamic(() => import('../components/ckeditor'), {
  ssr: false,
})

export default function Admin() {

  return (
    <div className="mx-auto w-4/5 h-screen">
      <Head>
        <title>MEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <CKEditorApp />
    </div>
  );
}
