import Head from "next/head";

import { React, useRef } from "react";
import { Editor } from "@tinymce/tinymce-react";

export default function Admin() {
  const editorRef = useRef(null);
  const log = () => {
    if (editorRef.current) {
      console.log(editorRef.current.getContent());
    }
  };

  return (
    <div className="mx-auto w-4/5 h-screen">
      <Head>
        <title>MEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-lg mx-auto space-y-5 grid-rows-3">
        <div>
          <h1 className="text-3xl">Welcome to Admin Panel</h1>
        </div>

        <div>
          {/* başlık */}
          <h1>Başlık</h1>
          <input
            type="text"
            className="w-full py-2 px-2 font-semibold text-2xl border-2 outline-none rounded-md focus:border-green-400 duration-300"
          ></input>
        </div>
        <div>
          {/* içerik */}
          <h1>İçerik</h1>
          
            <Editor
              apiKey="7l7ualj2gfk73lkw8949jgsds3ql74yyamx2842aosy6kmi7"
              onInit={(evt, editor) => (editorRef.current = editor)}
              initialValue=""
              init={{
                height: 500,
                menubar: false,
                plugins: [
                  "advlist",
                  "autolink",
                  "lists",
                  "link",
                  "image",
                  "charmap",
                  "preview",
                  "anchor",
                  "searchreplace",
                  "visualblocks",
                  "code",
                  "fullscreen",
                  "insertdatetime",
                  "media",
                  "table",
                  "code",
                  "help",
                  "wordcount",
                ],
                toolbar:
                  "undo redo | blocks | " +
                  "bold italic forecolor | alignleft aligncenter " +
                  "alignright alignjustify | bullist numlist outdent indent | " +
                  "removeformat | help",
                content_style:
                  "body { font-family:Helvetica,Arial,sans-serif; font-size:20px }",
              }}
            />
         

          <button
            onClick={log}
            className="border-2 w-full py-5 mt-5 text-xl font-semibold hover:text-white outline-none rounded-md focus:border-green-400 hover:bg-green-400 duration-300"
          >
            Submit
          </button>
        </div>
      </div>
    </div>
  );
}
