import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  
  return (
    <div className="flex flex-col w-full h-screen">
      <Head>
        <title>MEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl">
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
    <Link href="./articles">
      <button
        onClick={() => {
          
        }}
        className="border bg-red-600 text-white w-80 rounded-md p-3 shadow-lg hover:shadow-2xl duration-500"
      >
        Articles
      </button>
    </Link>
      
      
    </div>
  );
}
