import Head from "next/head";
import Link from "next/link";
import { server } from "../config";
import Image from "next/image"
import hello from '../images/hello.gif'
import instagramPNG from '../images/instagram.png';
import linkedinPNG from '../images/linkedin.png';
import githubPNG from '../images/github.png';
import mailPNG from '../images/mail.png';


export default function Home({ data }) {
  return (
    <div className=" bg-[#ffffff] w-full h-full scroll-smooth">
      <Head>
        <title>Mustafa Emir Akay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="container" className="bg-[#ffffff] w-full h-full">
        <div className="w-full flex h-60 align-top bg-[#222831] items-center mx-auto">
          <div className="mx-auto grid-row-3 grid-col-1 gap-x-5 grid">
            <div className="flex text-3xl text-white text-center align-middle justify-center">
              Merhaba ben Emir,
              <Image
                src={hello}
                alt="Hello"
                width={40}
                height={40}
              />

            </div>
            <div className="flex font-light text-center align-middle justify-center text-white text-2xl">
              Burada yazılım, spor ve felsefe gibi farklı konularda bildiklerimi
              ve deneyimlerimi paylaşıyorum.
            </div>
            <div className="flex font-light text-center align-middle justify-center text-white text-2xl grid-rows-1 grid-cols-4 gap-6 pt-6">

              <a href="https://github.com/MEmirAkay" className="border-2 rounded-full w-16 h-16 border-white items-center text-center flex justify-center hover:border-[#F05454] duration-150">

                <Image
                  src={githubPNG}
                  alt="Github"
                />

              </a>


              <a
                href="https://www.linkedin.com/in/mustafaemirakay/"
                className="border-2 rounded-full w-16 h-16 border-white items-center text-center flex justify-center hover:border-[#F05454] duration-150"
              >
                <Image
                  src={linkedinPNG}
                  alt="Linkedin"

                />

              </a>

              <a href="https://www.instagram.com/emirakay99/"
                className="border-2 rounded-full w-16 h-16 border-white items-center text-center flex justify-center hover:border-[#F05454] duration-150"
              >
                <Image
                  src={instagramPNG}
                  alt="Instagram"

                />
              </a>

              <a href="mailto:emirakay073@gmail.com"
                className="border-2 rounded-full w-16 h-16 border-white items-center text-center flex justify-center hover:border-[#F05454] duration-150"
              >
                <Image
                  src={mailPNG}
                  alt="Mail"

                />
              </a>

            </div>
          </div>
        </div>

        <div id="content" className="xl:w-8/12 lg:w-9/12 w-10/12 py-10 h-auto align-top mx-auto duration-300  ">
          {/* Content List Starts */}
          {data &&
            data.map((e) => (
              <div key={e._id}>
                <Link href="/article/[id]" as={`/article/${e._id}`}>
                  <div className="hover:shadow-2xl shadow-xl grid-cols-2 m-5 flex text-[#30475E] font-light md:text-2xl text-sm border-2 rounded-3xl border-[#30475E] hover:border-[#F05454] hover:text-[#F05454] duration-300">
                    <div id="image" className="p-5 lg:block hidden duration-300 ">
                      <Image
                        alt="picture"

                        loader={() => {
                          return `${e.pictureurl}`

                        }}
                        
                        src="me.png"
                        width={400}
                        height={300}
                        className="rounded-lg shadow-xl min-w-[400px] min-h-[300px] max-w-[400px] max-h-[300px] object-fit "/>

                      
                    </div>
                    <div className="grid-rows-3 p-5">
                      <div className="text-2xl md:font-semibold font-normal">
                        {e.header}
                      </div>
                      <div className=" md:text-xl text-base " dangerouslySetInnerHTML={{ __html: e.content.substring(0, 200) + "..." }}></div>
                      <div className="text-base">{e.date}</div>
                    </div>
                  </div>
                </Link>
              </div>
            ))}
          {/* Content List Ends */}
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`${server}/api/hello`, {
    method: "GET",
  });
  try {
    const data = await res.json();

    return {
      props: {
        data,
      },
    };
  } catch (err) {
    console.log("Error: ", err.message);
    return err.message;
  }
}
