import Head from "next/head";
import Link from "next/link";
import { Component, React, useEffect, useState } from "react";
import { useRouter } from 'next/router'

export default function Login() {
    const router = useRouter();

    useEffect(() => {
        control();
    },[])

    function control(){

        try {
            if (typeof localStorage.getItem('api_token') !== "undefined" && typeof localStorage.getItem('api_token') !== "undefined" && localStorage.getItem("login_token") !== null && localStorage.getItem("api_token") !== null) {
                fetch("/api/admin/token", {
                    method: "POST",
                    body: JSON.stringify({
                        login_token: localStorage.getItem('login_token'),
                        api_token: localStorage.getItem('api_token')
                    })
                })
                    .then((response) => response.json())
                    .then((responseJSON) => {
                        console.log("Status : ", responseJSON.status);
                        if(responseJSON.status == "Success"){
                            router.push("/admin");
                        }

                    }).catch(() => { console.log("Unauthorized") })
            }
        } catch (error) {
            alert("Please Log-in");
        }
    }

    function submitFunc(username, password){

        fetch("/api/admin/login", {
            method: "POST",
            body: JSON.stringify({
                username: username,
                password: password
            })
        })
            .then((response) => response.json())
            .then((responseJSON) => {

                if (responseJSON.status == "Success") {

                    localStorage.setItem('login_token', JSON.stringify(responseJSON.login_token))
                    localStorage.setItem('api_token', JSON.stringify(responseJSON.api_token))
                    router.push("/admin");
                }else{
                    alert("Wrong Username or Password")
                }


            }).catch((e) => { alert(e) })
    }

        let [username, setUsername] = useState("");
        let [password, setPassword] = useState("");

     return (
        <div className="w-full h-full pt-10">
            <Head>
                <title>MEA</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto w-9/12">
                <div className="flex flex-col justify-center my-auto align-middle ">

                    <div className="text-center">
                        <h1 className="text-2xl">Admin Panel</h1>
                    </div>
                    <div className="p-2">
                        <input
                            required
                            name="username"
                            value={username}
                            onChange={(e) => { setUsername(e.target.value) }}
                            type="text"
                            placeholder="Username"
                            className="w-full py-2 px-2 font-light text-2xl border-2 outline-none rounded-md focus:border-green-400 duration-300"
                        ></input>
                    </div>
                    <div className="p-2">
                        <input
                            required
                            name="password"
                            value={password}
                            onChange={(e) => { setPassword(e.target.value) }}
                            type="password"
                            placeholder="Password"
                            className="w-full py-2 px-2 font-light text-2xl border-2 outline-none rounded-md focus:border-green-400 duration-300"
                        ></input>
                    </div>
                    <div className="p-2">
                        
                            <button
                                onClick={() => {submitFunc(username, password) }}
                                type="submit"
                                value="Submit"
                                className="border-2 hover:border w-full py-5 mt-5 text-xl font-semibold hover:text-white outline-none rounded-md focus:border-green-400 hover:bg-green-400 duration-300">
                                Login
                            </button>
                        

                    </div>

                </div>
            </div>


        </div>
    );
}



