import Head from "next/head";
import { Component, React, useEffect } from "react";

class Login extends Component {
    constructor(props) {
        super(props);

        this.state = { username: "", password: "", loginStatus: "Fail" }

        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);

    }

    handleChange(event) {
        const target = event.target;
        const value = target.value;
        const name = target.name;

        this.setState({ [name]: value });
    }

    handleSubmit(event) {
        fetch("/api/admin/login", {
            method: "POST",
            body: JSON.stringify({
                username: this.state.username,
                password: this.state.password
            })
        })  .then((response) => response.json())
            .then((responseJSON) => {
                console.log(responseJSON);
            })



        event.preventDefault();
    }

    render() {
        return (
            <div className="w-full h-full pt-10">
                <Head>
                    <title>MEA</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="mx-auto w-9/12">
                    <div className="flex flex-row justify-center my-auto align-middle ">

                        <form onSubmit={this.handleSubmit}>
                            <div className="text-center">
                                <h1 className="text-2xl">Admin Panel</h1>
                            </div>
                            <div className="p-2">
                                <input
                                    name="username"
                                    value={this.state.username}
                                    onChange={this.handleChange}
                                    type="text"
                                    placeholder="Username"
                                    className="w-full py-2 px-2 font-light text-2xl border-2 outline-none rounded-md focus:border-green-400 duration-300"
                                ></input>
                            </div>
                            <div className="p-2">
                                <input
                                    name="password"
                                    value={this.state.password}
                                    onChange={this.handleChange}
                                    type="password"
                                    placeholder="Password"
                                    className="w-full py-2 px-2 font-light text-2xl border-2 outline-none rounded-md focus:border-green-400 duration-300"
                                ></input>
                            </div>
                            <div className="p-2">
                                <button

                                    type="submit"
                                    value="Submit"
                                    className="border-2 hover:border w-full py-5 mt-5 text-xl font-semibold hover:text-white outline-none rounded-md focus:border-green-400 hover:bg-green-400 duration-300"
                                >
                                    Login
                                </button>
                            </div>

                        </form>
                        
                    </div>

                </div>


            </div>
        );
    }

}




export default Login;
