import Head from "next/head";
import { React } from "react";
import dynamic from "next/dynamic";
import { server } from "../config";
import Link from "next/dist/client/link";
import { useRouter } from "next/router";
import leftArrowRed from "../../../images/leftArrowRed.png";
import Image from "next/image";

const CKEditorApp = dynamic(() => import("../components/ckeditor"), {
    ssr: false,
});

export default function SubmitNew() {

    const router = useRouter();

    return (
        <div className="w-full h-full pt-4">
            <Head>
                <title>MEA</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href="/admin">
                <div className="mx-auto border-2 rounded-full sm:w-14 sm:h-14 md:w-16 md:h-16  w-11/12 h-18  border-[#E5E7EB] items-center text-center flex justify-center hover:border-[#F05454] duration-150 p-2 sm:ml-10">
                    <Image
                        src={leftArrowRed}

                    />
                </div>
            </Link>
            <div className="mx-auto sm:w-9/12 w-11/12 py-10">
                <CKEditorApp router={router} />
            </div>
        </div>
    );
}


