import { Router, useRouter } from "next/router";
import { server } from "../../../config";
import Head from "next/head";
import Link from "next/link";

const article = ({ article }) => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div className="">
      <Head>
        <title>MEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid gap-4 grid-cols-1 grid-rows-2 w-full h-full ">
        <div>
          <div className="w-full">
            <img
              class="w-full object-cover"
              src={article.pictureurl}
              alt="Man looking lifting kettlebell"
            />
          </div>
          <div className="grid-rows-3">
            <div>
              <h1 className="font-bold text-center text-3xl">
                {article.header}
              </h1>
            </div>
            <div className="grid-cols-2 grid-rows-1">
              <div>{article.name}</div>
              <div>{article.date}</div>
            </div>
            <div dangerouslySetInnerHTML={{ __html: article.content }}></div>
          </div>
        </div>
      </div>

     
    </div>
  );
};

export const getServerSideProps = async (context) => {
  const res = await fetch(`${server}/api/articles/${context.params.id}`, {
    method: "GET",
  });
  try {
    const article = await res.json();
    return {
      props: {
        article,
      },
    };
  } catch (err) {
    console.log("Error: ", err.message);
    return err.message;
  }
};

export default article;
